title: Blog Severin
author: Severin Alexander BÃ¼hler
email: severin@feoh.io
description: > # this means to ignore newlines until "baseurl:"
  Blog for Lightning Network and LnRouter.app posts.

# social links
twitter_username: SeverinAlexB # DO NOT include the @ character, or else the build will fail!
github_username:  SeverinAlexB # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
